import * as FileSystem from 'expo-file-system/legacy'
import { API_URL } from '../constants'

const CACHE_FOLDER = 'identa-patient-photos'
const inFlight = new Map<string, Promise<string>>()
let cacheGeneration = 0
let directoryReady: Promise<string> | null = null
let cleanupPromise: Promise<void> = Promise.resolve()

function cacheDirectory(): string {
  if (!FileSystem.cacheDirectory) {
    throw new Error('Patient photo cache is unavailable')
  }
  return `${FileSystem.cacheDirectory}${CACHE_FOLDER}/`
}

function hashKey(value: string): string {
  let hash = 2166136261
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }
  return (hash >>> 0).toString(36)
}

function ensureCacheDirectory(): Promise<string> {
  if (!directoryReady) {
    directoryReady = cleanupPromise.then(async () => {
      const directory = cacheDirectory()
      await FileSystem.makeDirectoryAsync(directory, { intermediates: true })
      return directory
    })
  }
  return directoryReady
}

/**
 * Downloads an authenticated patient photo before handing it to React Native
 * Image. Android's native image pipeline can drop Authorization headers while
 * resolving protected media; FileSystem keeps the request explicit and gives
 * the image component a local URI instead.
 */
export function loadProtectedPatientPhoto(
  remoteUri: string,
  accessToken: string,
  ownerKey: string
): Promise<string> {
  const generation = cacheGeneration
  const requestKey = `${ownerKey}|${remoteUri}`
  const existing = inFlight.get(requestKey)
  if (existing) return existing

  const request = (async () => {
    const directory = await ensureCacheDirectory()
    const localUri = `${directory}${hashKey(requestKey)}.img`
    const cached = await FileSystem.getInfoAsync(localUri)
    if (cached.exists && cached.size > 0) return localUri
    if (cached.exists) {
      await FileSystem.deleteAsync(localUri, { idempotent: true }).catch(() => {})
    }

    let result: FileSystem.FileSystemDownloadResult
    try {
      result = await FileSystem.downloadAsync(remoteUri, localUri, {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: 'image/*',
        },
      })
    } catch (error) {
      await FileSystem.deleteAsync(localUri, { idempotent: true }).catch(() => {})
      throw error
    }

    if (result.status < 200 || result.status >= 300 || generation !== cacheGeneration) {
      await FileSystem.deleteAsync(localUri, { idempotent: true }).catch(() => {})
      throw new Error(`Patient photo download failed (${result.status})`)
    }

    return result.uri
  })().finally(() => {
    if (inFlight.get(requestKey) === request) inFlight.delete(requestKey)
  })

  inFlight.set(requestKey, request)
  return request
}

// Patient media URLs can be generated by Laravel with an origin that is not
// reachable from the phone (for example localhost behind a reverse proxy).
// Keep the authenticated API path and rebase it onto the configured mobile
// API origin before downloading it.
export function normalizeProtectedPatientMediaUri(uri: string): string {
  const marker = '/api/v1/patients/'
  const mediaPathIndex = uri.indexOf(marker)
  const apiPathIndex = API_URL.indexOf('/api/v1')
  if (mediaPathIndex < 0 || apiPathIndex < 0) return uri
  return `${API_URL.slice(0, apiPathIndex)}${uri.slice(mediaPathIndex)}`
}

/** Clears sensitive patient-photo files whenever the authenticated user exits. */
export function clearProtectedPatientPhotoCache(): Promise<void> {
  cacheGeneration += 1
  inFlight.clear()
  directoryReady = null
  cleanupPromise = cleanupPromise.then(async () => {
    if (!FileSystem.cacheDirectory) return
    await FileSystem.deleteAsync(`${FileSystem.cacheDirectory}${CACHE_FOLDER}/`, {
      idempotent: true,
    }).catch(() => {})
  })
  return cleanupPromise
}
